<?php

declare(strict_types=1);

/**
 * @file
 * Provides a relationship entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function relationship_theme(): array {
  return [
    'relationship' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for relationship templates.
 *
 * Default template: relationship.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the relationship information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_relationship(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

